FROM debian:bullseye-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    tshark \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY capture_baseline.sh .
RUN chmod +x capture_baseline.sh

ENTRYPOINT ["./capture_baseline.sh"]