services:

  broker:
    image: redis:alpine
    # force not snapshot
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - nids-internal
    ports:
      - "6379:6379"
      
  trainer:
    build: .
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./scripts:/app/scripts
    command: >
      sh -e -c "
      chmod +x ./get_data.sh && 
      ./get_data.sh && 
      echo '>>> Starting SVM Training...' &&
      python -m scripts.trainer.train
      "

  # this might need sampling algorithm to sniff packages or horizontal scales?
  sniffer:
    build: .
    networks:
      - nids-internal
    cap_add:
      - NET_ADMIN  # Required to run 'ip link set'
      - NET_RAW    # Required for Scapy to sniff
    volumes:
      - ./scripts:/app/scripts
    environment:
      - PYTHONUNBUFFERED=1 # stop python from buffering output
      - PYTHONPATH=/app
    entrypoint: /bin/sh -c "ip link set eth0 promisc on && python -m scripts.sniffer.sniffer"
    depends_on:
      svm-service:
        condition: service_started
      broker:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  svm-service:
    build: .
    networks:
      - nids-internal
    restart: always
    volumes:
      - ./models:/app/models
      - ./scripts:/app/scripts
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python scripts/svm/worker.py
    depends_on:
      trainer:
        condition: service_completed_successfully
      broker:
        condition: service_started

networks:
  nids-internal:
    driver: bridge