"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PacketInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SRC_IP_FIELD_NUMBER: _builtins.int
    DST_IP_FIELD_NUMBER: _builtins.int
    SRC_PORT_FIELD_NUMBER: _builtins.int
    DST_PORT_FIELD_NUMBER: _builtins.int
    FEATURES_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    timestamp: _builtins.float
    src_ip: _builtins.str
    dst_ip: _builtins.str
    src_port: _builtins.int
    dst_port: _builtins.int
    @_builtins.property
    def features(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        timestamp: _builtins.float = ...,
        src_ip: _builtins.str = ...,
        dst_ip: _builtins.str = ...,
        src_port: _builtins.int = ...,
        dst_port: _builtins.int = ...,
        features: _abc.Iterable[_builtins.float] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dst_ip", b"dst_ip", "dst_port", b"dst_port", "features", b"features", "src_ip", b"src_ip", "src_port", b"src_port", "task_id", b"task_id", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PacketInfo: _TypeAlias = PacketInfo  # noqa: Y015
