kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: nids-cluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/nonroot/work/network_attack_detection
      containerPath: /home/nonroot/work/network_attack_detection