apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniffer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sniffer
  template:
    metadata:
      labels:
        app: sniffer
    spec:
      # Used hostnetwork here to isolate from in cluster heartbeat traffic
      hostNetwork: true 
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: sniffer
        image: kind-registry:5000/nids-main:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        # args: 
          # - "ip link set eth0 promisc on && python -m scripts.sniffer.sniffer"
        args: 
          - |
            if ! ip link show eth1 > /dev/null 2>&1; then
                echo "eth1 not found. Creating dummy interface..."
                ip link add eth1 type dummy || true
                ip link set eth1 up || true
                ip link set eth1 promisc on || true
            else
                echo "eth1 already exists. Using existing interface."#
                ip link set eth1 up || true
            fi

            python -m scripts.sniffer.sniffer
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: REDIS_HOST
          value: "broker.default.svc.cluster.local"
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: scripts-storage
          mountPath: /app/scripts
      volumes:
      - name: scripts-storage
        hostPath:
          path: ${PROJECT_ROOT}/scripts
          type: Directory