apiVersion: batch/v1
kind: Job
metadata:
  name: traffic-generator
spec:
  template:
    spec:
      hostNetwork: true
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/sh", "-c"]
        args:
          - |
            apk add tcpreplay
            ip link delete eth1 2>/dev/null || true;
            ip link add eth1 type dummy || true;
            ip link set eth1 up || true;
            ip link set eth1 promisc on || true;
            tcpreplay --intf1=eth1 --pps=5000 /data/Mirai_pcap.pcap
        volumeMounts:
        - name: pcap-data
          mountPath: /data
      volumes:
      - name: pcap-data
        hostPath:
          path: ${PROJECT_ROOT}/data
          type: Directory
      restartPolicy: Never