apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    {{- include "nids.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}-broker
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.redisExporter.port }}
      targetPort: {{ .Values.redisExporter.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    {{- include "nids.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-broker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-broker
    spec:
      containers:
      # --- Container 1: The Broker ---
      - name: redis
        image: {{ .Values.redis.image }}
        args: {{ .Values.redis.args | toJson }}
        ports:
        - containerPort: {{ .Values.redis.port }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
      # --- Container 2: The Sidecar Exporter ---
      - name: redis-exporter
        image: {{ .Values.redisExporter.image }}
        env:
        - name: REDIS_ADDR
          value: "redis://localhost:6379"
        ports:
        - name: metrics
          containerPort: {{ .Values.redisExporter.port }}