FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache procps

COPY sinker/go.mod sinker/go.sum ./
RUN go mod download

COPY sinker/ .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/sinker_bin .

FROM alpine:latest
WORKDIR /root/

RUN apk --no-cache add ca-certificates
COPY --from=builder /app/sinker_bin .
CMD ["./sinker_bin"]