{{- if .Values.database.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-timescale-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.database.storage }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - name: timescale
        image: {{ .Values.database.image }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.database.dbName | quote }}
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: db-storage
        {{- if .Values.database.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-timescale-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: init-script
        configMap:
          name: db-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432