apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kitnet-worker
spec:
  replicas: {{ .Values.workers.kitnet.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kitnet-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kitnet-worker
    spec:
      initContainers:
      - name: wait-for-kitnet
        image: busybox
        command: ['sh', '-c', 'until [ -f /app/models/kitnet_state.pkl ]; do echo waiting for trainer; sleep 2; done;']
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      containers:
      - name: kitnet-worker
        image: {{ .Values.workers.kitnet.image }}
        command: ["python", "scripts/kitnet/kitnet_worker.py"]
        env:
        - name: REDIS_ADDR
          value: "{{ .Release.Name }}-broker:6379"
        - name: MODEL_DIR
          value: "/app/models"
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        hostPath:
          path: {{ .Values.global.projectRoot }}/models
          type: Directory