apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-exporter
spec:
  selector:
    app: {{ .Release.Name }}-redis-exporter
  ports:
    - port: {{ .Values.redisExporter.port }}
      targetPort: {{ .Values.redisExporter.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis-exporter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: {{ .Values.redisExporter.image }}
        env:
        - name: REDIS_ADDR
          value: "redis://{{ include "nids.redisAddr" . }}"
        ports:
        - containerPort: {{ .Values.redisExporter.port }}